# this workflow is intended to test the behavior of the system when a large artifact is submitted for signing
# besides other aspects it helps to check signed artifacts downloading back to the runner
name: e2e big exe tests

on:
    workflow_dispatch:
      inputs:
        environment:
          required: true
          type: string
        workflow-dispatch-event-id:
          required: true
          type: string
        connector-url:
          required: true
          type: string
          description: 'SignPath connector URL'
        comment:
          required: false
          type: string
          default: '<no comment>'
jobs:
  call-base-workflows:
    uses: ./.github/workflows/e2e-workflow-base.yml
    secrets:
      SIGNPATH_API_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}
      SIGNPATH_TOKEN_ENCRYPTION_KEY: ${{ secrets.SIGNPATH_TOKEN_ENCRYPTION_KEY }}
    with:
      workflow-dispatch-event-id: ${{ inputs.workflow-dispatch-event-id }}
      environment: ${{ inputs.environment }}
      comment: ${{ inputs.comment }}
  build-and-sign:
    uses: ./.github/workflows/build-and-sign-reusable.yml
    secrets:
      SIGNPATH_API_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}
    with:
      environment: ${{ inputs.environment }}
      connector-url: ${{ inputs.connector-url }}
      artifact-path: ./artifacts/big.exe
      signing-policy-slug: e2e-test-sp
      output-artifact-directory: signed-artifact
